# Generated by Django 5.0.4 on 2024-04-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=models.URLField(blank=True, null=True),
        ),
    ]
