# Generated by Django 5.0.4 on 2024-04-26 13:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_brand_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"ordering": ["-name"]},
        ),
    ]
