# Generated by Django 5.0.4 on 2024-04-26 14:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_brand_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={"ordering": ["name"]},
        ),
    ]
