# Generated by Django 5.0.4 on 2024-04-26 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_alter_brand_logo_category_item"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="brand",
        ),
        migrations.AddField(
            model_name="category",
            name="brand",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.brand",
            ),
        ),
    ]
