# Generated by Django 5.0.4 on 2024-04-26 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_remove_category_brand_category_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="brand",
            field=models.ForeignKey(
                default="NA",
                on_delete=django.db.models.deletion.CASCADE,
                to="product.brand",
            ),
        ),
    ]
