# Generated by Django 5.0.4 on 2024-04-27 03:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_gender_category_gender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brand",
            options={
                "ordering": ["name"],
                "verbose_name": "Brand",
                "verbose_name_plural": "Brands",
            },
        ),
    ]
