# Generated by Django 5.0.4 on 2024-04-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "product",
            "0013_alter_item_brand_alter_item_price_alter_item_rating_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="brand",
        ),
        migrations.AddField(
            model_name="category",
            name="brand",
            field=models.ManyToManyField(to="product.brand"),
        ),
    ]
