# Generated by Django 5.0.4 on 2024-04-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0014_remove_category_brand_category_brand"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="gender",
        ),
        migrations.AddField(
            model_name="category",
            name="gender",
            field=models.ManyToManyField(to="product.gender"),
        ),
    ]
