# Generated by Django 5.0.4 on 2024-04-27 03:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0015_remove_category_gender_category_gender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["category_type"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ["name"],
                "verbose_name": "Item",
                "verbose_name_plural": "Items",
            },
        ),
    ]
