# Generated by Django 5.0.4 on 2024-04-27 03:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0016_alter_category_options_alter_item_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_sold",
            field=models.BooleanField(default=False),
        ),
    ]
