# Generated by Django 5.0.4 on 2024-04-28 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0017_item_is_sold"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="category",
            name="gender",
        ),
        migrations.AddField(
            model_name="category",
            name="brand",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.brand",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="gender",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.gender",
            ),
        ),
    ]
