# Generated by Django 5.0.4 on 2024-04-28 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0018_remove_category_brand_remove_category_gender_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="brand",
        ),
        migrations.RemoveField(
            model_name="category",
            name="gender",
        ),
        migrations.AddField(
            model_name="item",
            name="gender",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.gender",
            ),
        ),
    ]
