# Generated by Django 5.0.4 on 2024-06-05 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="gender",
            field=models.CharField(
                choices=[("unisex", "Unisex"), ("male", "Male"), ("female", "Female")],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="rating",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="size",
            field=models.CharField(
                choices=[
                    ("s", "S"),
                    ("xxl", "XXL"),
                    ("m", "M"),
                    ("l", "L"),
                    ("xxxl", "XXXL"),
                    ("4xl", "4XL"),
                    ("3xl", "3XL"),
                    ("xl", "XL"),
                    ("xs", "XS"),
                ],
                max_length=255,
            ),
        ),
    ]
