# Generated by Django 5.0.4 on 2024-06-05 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_item_gender_alter_item_rating_alter_item_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand",
                to="store.brand",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="store.category",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="gender",
            field=models.CharField(
                choices=[("unisex", "Unisex"), ("male", "Male"), ("female", "Female")],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="size",
            field=models.CharField(
                choices=[
                    ("4xl", "4XL"),
                    ("xxl", "XXL"),
                    ("s", "S"),
                    ("xs", "XS"),
                    ("l", "L"),
                    ("m", "M"),
                    ("xl", "XL"),
                    ("xxxl", "XXXL"),
                    ("3xl", "3XL"),
                ],
                max_length=255,
            ),
        ),
    ]
