# Generated by Django 5.0.4 on 2024-06-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_alter_item_gender_alter_item_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="gender",
            field=models.CharField(
                choices=[("female", "Female"), ("unisex", "Unisex"), ("male", "Male")],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="size",
            field=models.CharField(
                choices=[
                    ("l", "L"),
                    ("4xl", "4XL"),
                    ("s", "S"),
                    ("xxl", "XXL"),
                    ("xl", "XL"),
                    ("xs", "XS"),
                    ("3xl", "3XL"),
                    ("m", "M"),
                    ("xxxl", "XXXL"),
                ],
                max_length=255,
            ),
        ),
    ]
