# Generated by Django 5.0.4 on 2024-07-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_product_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="quantity",
            field=models.BigIntegerField(default=1, null=True),
        ),
    ]
