# Generated by Django 5.0.4 on 2024-07-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_cart", "0002_remove_cart_items_cart_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
