# Generated by Django 5.0.4 on 2024-07-05 13:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_myuser_email_alter_myuser_username"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyUser",
        ),
    ]
